### ISSUE TITLE
Installation of Graphviz for model visualization

### ISSUE THREAD

**Issue by olivier-boisard** [windj007/docker-jupyter-keras-tools#2]
Hi,

First, thanks a lot for this. It just works!

I do have one suggestion: it'd be nice to have directly in the docker the library needed by keras to display the model, i.e. pydot and graphviz?  More info about this [there](https://keras.io/visualization/).

Cheers,
Olivier

**Comment by windj007** [comment]
Thank you very much, I'm glad to hear that somebody is using it!
No problem, I'll add it!

As a workaround I often have the first cell in Jupyter Notebook with code like the following:

```
!pip install -U pydot
!apt-get install -yqq some-other-ubuntu-package
```
